import React, { useEffect, useRef, useState } from 'react'
import { api, speak, stopSpeaking } from '../api.js'
import Icon from './Icon.jsx'
import { isOnlineQuery } from '../lib/online.js'
const starters=['今天有点累，陪我聊聊吧','想和你分享一件开心的事','播报今天的每日新闻']
export default function Chat({boot,companion,messages,sending,err,autoplay,onToggleAutoplay,onSend,hfOn,hfState,micLevel,onToggleHf,onInterrupt,onOpenConnection,onRetry,onMemorySaved,headphones,immersive=false,onFullConversation,speechCaption=''}) {
 const [input,setInput]=useState(''),[query,setQuery]=useState(''),[searchOpen,setSearchOpen]=useState(false),[notice,setNotice]=useState(''),[playingId,setPlayingId]=useState(null),[follow,setFollow]=useState(true)
 const listRef=useRef(null),fieldRef=useRef(null)
 const [typing,setTyping]=useState(false),[captions,setCaptions]=useState(true)
 const dockRef=useRef(null),[dockHeight,setDockHeight]=useState(38)
 useEffect(()=>{if(!immersive||!dockRef.current)return;const observer=new ResizeObserver(entries=>setDockHeight(Math.ceil(entries[0].target.getBoundingClientRect().height)));observer.observe(dockRef.current);return()=>observer.disconnect()},[immersive])
 useEffect(()=>{if(immersive&&typing)fieldRef.current?.focus()},[immersive,typing])
 useEffect(()=>{if(!query&&follow&&listRef.current){const el=listRef.current,last=messages.at(-1);if(last?.online?.bulletin){const article=el.querySelector('.conversation-message:last-of-type');if(article)el.scrollTop+=article.getBoundingClientRect().top-el.getBoundingClientRect().top-8}else el.scrollTop=el.scrollHeight}},[messages,sending,query,follow])
 useEffect(()=>()=>stopSpeaking(),[])
 useEffect(()=>{const focus=()=>fieldRef.current?.focus();window.addEventListener('xinyu-focus-chat',focus);return()=>window.removeEventListener('xinyu-focus-chat',focus)},[])
 const send=()=>{if(!input.trim())return;onSend(input);setInput('');setFollow(true)}
 const replay=async m=>{if(playingId===m.id){stopSpeaking();setPlayingId(null);return}onInterrupt();setPlayingId(m.id);setNotice('');try{if(!await speak(m.online?.speech_text || m.content))setNotice('播放已停止或未完成')}catch{setNotice('语音暂时不可用，请在内测检查中测试')}setPlayingId(id=>id===m.id?null:id)}
 const copy=async text=>{try{await navigator.clipboard.writeText(text);setNotice('已复制')}catch{setNotice('复制失败，可选中文字手动复制')}}
 const remember=async m=>{try{await api.addMemory((m.role==='user'?'用户说：':'与'+companion.name+'的对话：')+m.content.slice(0,460));setNotice('已加入专属记忆，可前往记忆页修改');onMemorySaved?.()}catch(e){setNotice(e.message)}}
 const all=messages.filter(m=>!query||m.content.toLowerCase().includes(query.toLowerCase()))
 const status={connecting:'正在开启麦克风',listening:'麦克风已开启 · 我在听',hearing:'正在听你说',transcribing:'正在识别这句话',thinking:'正在想怎么回应',preparing:'正在准备语音',speaking:companion.name+'正在说话',idle:'麦克风已暂停',error:'麦克风需要检查'}[hfState]||'麦克风已暂停'
 const busy=['speaking','thinking','preparing','transcribing'].includes(hfState)
 const latest=messages.at(-1)
 const caption=speechCaption&&hfState==='speaking'?speechCaption:latest?.content||'我在这里，你可以直接开口。'
 const captionName=speechCaption&&hfState==='speaking'?companion.name:latest?.role==='user'?'我':companion.name
 if(immersive)return <section className={'immersive-dialogue'+(typing?' typing':'')+(err?' has-alert':'')} aria-label="沉浸陪伴对话" style={{'--imm-dock-height':dockHeight+'px'}}>
   {captions&&<div className="immersive-caption" aria-live="polite" aria-atomic="true"><p data-speaker={captionName} aria-label={captionName+'的字幕'}>{caption.replace(/\s+/g,' ').trim()}</p></div>}
   <footer className="immersive-dock" ref={dockRef}>
     {err&&<div className="immersive-alert" role="alert"><span>{err}</span><button onClick={/模型|密钥|服务|回复/.test(err)?onOpenConnection:onRetry}>{/模型|密钥|服务|回复/.test(err)?'检查连接':'重试'}</button></div>}
     <div className="immersive-controls"><div className="immersive-state"><span className="voice-meter" aria-hidden="true">{[0,1,2,3,4].map(i=><i key={i} style={{height:4+micLevel*(10+(2-Math.abs(i-2))*6)+'px'}}/>)}</span><span><b>{status}</b><small>{hfOn?(headphones?'耳机模式 · 开口可打断':'外放保护 · 点停止插话'):'麦克风已暂停'}</small></span></div><div className="immersive-buttons">
       <button className="imm-button" aria-label={captions?'隐藏字幕':'显示字幕'} title={captions?'隐藏字幕':'显示字幕'} aria-pressed={captions} onClick={()=>setCaptions(v=>!v)}><span className="caption-icon">字</span></button>
       <button className="imm-button" aria-label={typing?'收起文字输入':'输入文字'} title={typing?'收起文字输入':'输入文字'} aria-expanded={typing} onClick={()=>setTyping(v=>!v)}><Icon name="chat" size={18}/></button>
       <button className={'imm-button'+(autoplay?' active':'')} aria-label="切换自动朗读" title={autoplay?'关闭自动朗读':'开启自动朗读'} onClick={onToggleAutoplay}><Icon name="sound" size={18}/></button>
       {busy&&<button className="imm-button stop" aria-label="打断回复" title="停止当前回复" onClick={onInterrupt}><Icon name="stop" size={18}/></button>}
       <button className={'imm-button'+(!hfOn?' muted':'')} aria-label={hfOn?'暂停麦克风':'开启麦克风'} title="Ctrl + Shift + M" onClick={onToggleHf}><Icon name={hfOn?'mic':'mute'} size={19}/></button>
     </div></div>
     {typing&&<form className="immersive-input" onSubmit={e=>{e.preventDefault();send()}}><input ref={fieldRef} aria-label="聊天消息" value={input} maxLength={2000} placeholder={'想对'+companion.name+'说点什么…'} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&e.nativeEvent.isComposing)e.preventDefault()}}/><button type="submit" aria-label="发送消息" disabled={!input.trim()||(!boot.llm_ready&&!isOnlineQuery(input)&&!boot.weather_pending)}><Icon name="arrow" size={20}/></button></form>}
   </footer>
 </section>
 return <section className="conversation-panel" aria-label="陪伴对话"><header className="conversation-head"><div><h2>我们的日常</h2><span>语音和文字，都接着聊</span></div><div className="conversation-tools"><button className={'icon-btn'+(searchOpen?' enabled':'')} aria-label="搜索聊天" title="搜索聊天" onClick={()=>setSearchOpen(v=>!v)}><Icon name="search" size={19}/></button><button className={'icon-btn'+(autoplay?' enabled':'')} aria-label="切换自动朗读" title={autoplay?'关闭自动朗读':'开启自动朗读'} onClick={onToggleAutoplay}><Icon name="sound" size={19}/></button></div></header>
 {!boot.llm_ready&&<div className="setup-banner"><Icon name="settings" size={20}/><div><b>天气与资讯已可联网查</b><p>日常陪伴仍需连接模型；天气和新闻可先试用。</p></div><button onClick={onOpenConnection}>去连接 <span>→</span></button></div>}
 {searchOpen&&<div className="chat-search"><Icon name="search" size={16}/><input aria-label="搜索最近聊天" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索最近 200 条聊天"/><span>{all.length} 条</span></div>}
 <div className="conversation-messages" ref={listRef} onScroll={e=>{const el=e.currentTarget;setFollow(el.scrollHeight-el.scrollTop-el.clientHeight<50)}}>
 {!messages.length&&!query&&<div className="conversation-empty"><div className="greeting-mark">“</div><h3>不用想好开场白。</h3><p>{boot.llm_ready?'直接说话，或在下面写一句。今天开心的、烦心的，都可以慢慢聊。':'可以先问天气、新闻或联网搜索；日常聊天请连接模型。'}</p><div className="starter-list">{starters.map(s=><button key={s} onClick={()=>{setInput(s);fieldRef.current?.focus()}}>{s}<span>↗</span></button>)}</div></div>}
 {all.map(m=><article key={m.id} className={'conversation-message '+(m.role==='user'?'me':'ta')}><div className="message-meta"><span>{m.role==='user'?'我':companion.name}</span>{m.ts&&<time>{new Date(m.ts).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</time>}</div><div className="message-text">{m.content}</div>{m.online&&<details className="online-evidence"><summary>联网{m.online.status==='error'?'查询失败':m.online.status==='clarification'?'需要补充信息':'查询'} · {m.online.checked_at?new Date(m.online.checked_at).toLocaleString('zh-CN'):''} · 查看来源</summary>{m.online.clock&&<p className="source-clock">{m.online.clock.verified?"日期已联网核对":"日期依据电脑系统时间 · 联网核时未成功"}</p>}{m.online.source_checks?.map(c=><p className={"source-check "+c.status} key={c.source}>{c.source} · {c.status==="connected"?"已连接（"+c.count+" 条）":"暂不可达"}</p>)}{m.online.sources?.map((s,i)=><a key={s.url+i} href={s.url} target="_blank" rel="noreferrer">[{i+1}] {s.title} <small>{s.publisher} · {s.published_at?new Date(s.published_at).toLocaleString('zh-CN'):'发布时间未核实'}</small></a>)}</details>}<div className="message-actions"><button title="复制" aria-label="复制消息" onClick={()=>copy(m.content)}><Icon name="copy" size={15}/></button><button title="存为记忆" aria-label="存为记忆" onClick={()=>remember(m)}><Icon name="memory" size={15}/></button>{m.role==='assistant'&&<button title="朗读" aria-label={playingId===m.id?'停止重播':'重播消息'} onClick={()=>replay(m)}><Icon name={playingId===m.id?'stop':'sound'} size={15}/></button>}</div></article>)}
 {query&&!all.length&&<div className="empty-state">没有找到相关聊天</div>}{sending&&<div className="thinking-note" role="status"><span/><span/><span/>{companion.name}正在回应</div>}</div>
 {err&&<div className="conversation-error" role="alert"><span>{err}</span><button onClick={/模型|密钥|服务|回复/.test(err)?onOpenConnection:onRetry}>{/模型|密钥|服务|回复/.test(err)?'检查连接':'重试麦克风'}</button></div>}
 {notice&&<div className="chat-notice" role="status">{notice}<button aria-label="关闭提示" onClick={()=>setNotice('')}>×</button></div>}
 <div className={'voice-strip '+hfState}><div className="voice-meter" aria-hidden="true">{[0,1,2,3,4].map(i=><i key={i} style={{height:4+micLevel*(12+(2-Math.abs(i-2))*8)+'px'}}/>)}</div><div className="voice-strip-copy"><b>{status}</b><small>{hfOn?(headphones?'耳机通话 · 开口可打断':'外放防回声 · 点停止插话，播完自动听'):'你仍然可以打字聊天'}</small></div>{busy&&<button className="voice-stop" aria-label="打断回复" title="停止当前回复" onClick={onInterrupt}><Icon name="stop" size={17}/></button>}<button className={'mic-toggle'+(!hfOn?' muted':'')} aria-label={hfOn?'暂停麦克风':'开启麦克风'} title="Ctrl + Shift + M" onClick={onToggleHf}><Icon name={hfOn?'mic':'mute'} size={19}/></button></div>
 <div className="inline-composer"><textarea ref={fieldRef} aria-label="聊天消息" value={input} rows={2} maxLength={2000} placeholder={'想对'+companion.name+'说点什么…'} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}}/><button aria-label="发送消息" disabled={!input.trim()||(!boot.llm_ready&&!isOnlineQuery(input)&&!boot.weather_pending)} title={boot.llm_ready||isOnlineQuery(input)||boot.weather_pending?'发送':'日常聊天请先连接模型'} onClick={send}><Icon name="arrow" size={21}/></button></div><footer className="input-foot">Enter 发送 · Shift + Enter 换行<span>天气/资讯会发送查询词联网</span></footer></section>
}
