import React, { useEffect, useState } from 'react'
import { api, speak, stopSpeaking } from '../api.js'
import { CHARACTERS, charFile } from '../lib/characters.js'
import Icon from './Icon.jsx'
export default function Wizard({boot,onDone}) {
 const [selected,setSelected]=useState(CHARACTERS.find(c=>c.id==='f3')||CHARACTERS[0]),[name,setName]=useState('晚晚'),[petname,setPetname]=useState(''),[relationship,setRelationship]=useState('知己'),[busy,setBusy]=useState(false),[err,setErr]=useState('')
 useEffect(()=>()=>stopSpeaking(),[])
 const choose=c=>{stopSpeaking();setSelected(c);setName(c.name)}
 const finish=async()=>{setBusy(true);setErr('');stopSpeaking();try{await api.saveCompanion({name:name.trim(),petname:petname.trim()||'你',relationship,gender:selected.gender,char:selected.id,voice:selected.voice,personality:selected.personality});await onDone()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 return <div className="welcome"><section className="welcome-art"><img src={charFile(selected.id)} alt={selected.name}/><div className="welcome-brand">♡ 心屿 <span>个人内测</span></div><div className="welcome-caption"><h1>从一句你好，<br/>开始熟悉。</h1><p>一个可以好好说话的地方。</p></div></section><section className="welcome-form"><div className="eyebrow">初次见面</div><h2>谁来陪你聊聊？</h2><p>先选择一位伙伴。名字、个性和声音，之后都可以调整。</p><div className="welcome-roles">{CHARACTERS.map(c=><button aria-pressed={selected.id===c.id} className={selected.id===c.id?'selected':''} key={c.id} onClick={()=>choose(c)}><img src={charFile(c.id)} alt=""/><b>{c.name}</b><small>{c.title}</small></button>)}</div><div className="settings-form"><div className="form-grid"><label>TA 的名字<input value={name} onChange={e=>setName(e.target.value)} maxLength={20}/></label><label>TA 怎么称呼你<input value={petname} onChange={e=>setPetname(e.target.value)} maxLength={20} placeholder="你的昵称（可选）"/></label></div><label>你们的相处方式<select value={relationship} onChange={e=>setRelationship(e.target.value)}>{['知己','恋人','朋友','生活搭子'].map(r=><option key={r}>{r}</option>)}</select></label></div><button className="text-button welcome-voice" onClick={async()=>{try{if(!await speak('你好，今天想聊点什么？',{voice:selected.voice}))setErr('声音试听未能完成')}catch{setErr('试听需要网络，可以稍后再试')}}}><Icon name="sound" size={18}/>听听 TA 的声音</button>{!boot.llm_ready&&<div className="setup-note"><Icon name="settings" size={20}/><p>下一步连接对话模型。内测版使用你自己的模型密钥；没有密钥也可以先浏览。</p></div>}{err&&<p className="hint-err" role="alert">{err}</p>}<button className="btn welcome-start" disabled={!name.trim()||busy} onClick={finish}>{busy?'正在准备…':boot.llm_ready?'进入陪伴':'选好了，继续'}<Icon name="arrow" size={18}/></button><small className="welcome-privacy">虚拟 AI 陪伴 · 记录保存在本机 · 当前无收费</small></section></div>
}